AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Employee Management Lambda Functions

Resources:
  AddEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.akrima.employeemanagement.AddEmployeeLambda::handleRequest
      Runtime: java17
      CodeUri: target/EmployeeManagementLambdaJava-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30

  UpdateEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.akrima.employeemanagement.UpdateEmployeeLambda::handleRequest
      Runtime: java17
      CodeUri: target/EmployeeManagementLambdaJava-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30

  RetrieveAllEmployeesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.akrima.employeemanagement.RetrieveAllEmployeesLambda::handleRequest
      Runtime: java17
      CodeUri: target/EmployeeManagementLambdaJava-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30

  RetrieveEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.akrima.employeemanagement.RetrieveEmployeeLambda::handleRequest
      Runtime: java17
      CodeUri: target/EmployeeManagementLambdaJava-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30

  DeleteEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.akrima.employeemanagement.DeleteEmployeeLambda::handleRequest
      Runtime: java17
      CodeUri: target/EmployeeManagementLambdaJava-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30
